# ESP32-H2 system configuration
# Note: H2 has no WiFi. Has BLE + 802.15.4 (Thread/Zigbee).

/system/update-rate rate=20
/system/log-level severity=trace

/protocol/telnet/server add name=console port=23
/apps/api add name=api http-server=webserver uri=/api
/tools/pcap/server add name=rpcap port=2002 allow-anonymous=true
