# Startup script

/system/update-rate rate=20
/system/log-level severity=trace

# add a login/password for testing
/secret/add name=test password=password services=admin,wifi,vpn,rpcap

# Configure serial streams for various RS485 bridges
/stream/tcp-client
add name=shelly remote=10.111.73.80:502

# Create modbus interfaces
/interface/modbus
add name=shelly stream=shelly protocol=tcp

# populate the modbus interfaces with devices
/interface/modbus/remote-server
add name=shelly interface=shelly address=0 universal-address=2 profile=shelly

# MQTT server
/protocol/mqtt/broker add name=mqtt port=1883
/secret add name=homeassistant password=qqqqqqqqqq services=mqtt


#------------------------------------------------------------------------------------------
# Setup 'devices' to sample and record data...

# Snoop the SolarEdge inverter
/protocol/modbus/client add name=shelly interface=shelly
/protocol/modbus/device add id=shelly client=shelly slave=shelly

# MQTT devices
#/protocol/mqtt/device add id=annex_univ_gpo broker=mqtt profile=open_beken device_id=obk68B4AF26

#------------------------------------------------------------------------------------------
# Other runtime stuff

/protocol/http/server add name=webserver port=8080
/protocol/telnet/server add name=console port=23
/protocol/dns/server add name=dns protocols=mdns#,llmnr,wins,dns,dot,doh doh-server=webserver doh-uri=/dns-query

/protocol/websocket/server add name=websock http-server=webserver uri=/ws
/apps/api add name=api http-server=webserver uri=/api
/tools/pcap/server add name=rpcap port=2002 allow-anonymous=true
